version: '3.8'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strapi-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - '1338:1338'
    volumes:
      - ./public/uploads:/app/public/uploads
